// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFJcIuKs0zGswPzgq-TewDGWbVi3c87sU',
    appId: '1:388256750244:web:2b3f08d95cc590cd286431',
    messagingSenderId: '388256750244',
    projectId: 'fir-auth-f4e34',
    authDomain: 'fir-auth-f4e34.firebaseapp.com',
    storageBucket: 'fir-auth-f4e34.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXGFZ3kMg6GX6IlIeAWOZYGICflWdvXpI',
    appId: '1:388256750244:android:be29f6a02c014755286431',
    messagingSenderId: '388256750244',
    projectId: 'fir-auth-f4e34',
    storageBucket: 'fir-auth-f4e34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtBMziX_b8jlvzEPL-2D817qGScin8epA',
    appId: '1:388256750244:ios:6128680aa94ecc9e286431',
    messagingSenderId: '388256750244',
    projectId: 'fir-auth-f4e34',
    storageBucket: 'fir-auth-f4e34.firebasestorage.app',
    iosBundleId: 'com.example.practice',
  );
}
